id: passthrough
version: 1.0.0
config-groups:
  default:
    test-param:
      label: Testing parameter
      mandatory: true
      type: single
      default: test
      visible: true
      validator: '[A-z\._]+'
      help: This is just a testing parameter